import { Inter, Ubuntu, Ubuntu_Condensed } from "next/font/google";
import StoreProvider from "./StoreProvider";
import NextTopLoader from "nextjs-toploader";
import ProgressBar from "./Components/ProgressBar";

import "./globals.css";

//import all of my Components I want on each page
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";

const inter = Inter({ subsets: ["latin"] });

const ubuntu = Ubuntu({
  weight: ["500","400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "TheJelly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <StoreProvider>
          <Navbar />
          <NextTopLoader
            color="#C058C6ff"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
            shadow="0 0 10px #2299DD,0 0 5px #2299DD"
          />

          <ProgressBar />

          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
